/**
 * Inlined in the document to capture beforeinstallprompt before React hydrates.
 * Kept as a string (not a public /pwa-install-init.js file) to avoid preload +
 * service-worker cross-world mismatch warnings in Chrome/Safari.
 *
 * Installed signals: standalone display-mode, appinstalled, remembered localStorage
 * (cleared only when beforeinstallprompt fires), and same-origin getInstalledRelatedApps.
 * Never treat service-worker presence alone as installed.
 */
export const PWA_INSTALL_INIT_SCRIPT = `(function(){if(typeof window==='undefined')return;var STORAGE_KEY='cosset-pwa-installed';var state=window.__cossetPwaInstall=window.__cossetPwaInstall||{deferredPrompt:null,installed:false,initialized:false};if(state.initialized)return;state.initialized=true;function notify(){window.dispatchEvent(new Event('cosset-pwa-install-change'))}function clearInstalled(){state.installed=false;try{localStorage.removeItem(STORAGE_KEY)}catch(e){}}function markInstalled(){state.installed=true;state.deferredPrompt=null;try{localStorage.setItem(STORAGE_KEY,'1')}catch(e){}notify()}function isStandalone(){var modes=['standalone','minimal-ui','fullscreen'];var standalone=modes.some(function(mode){return window.matchMedia&&window.matchMedia('(display-mode: '+mode+')').matches});return standalone||window.navigator.standalone===true}function rememberLocal(){try{if(localStorage.getItem(STORAGE_KEY)==='1'){state.installed=true;notify();return true}}catch(e){}return false}if(isStandalone()){markInstalled()}else{rememberLocal()}window.addEventListener('beforeinstallprompt',function(event){event.preventDefault();clearInstalled();state.deferredPrompt=event;notify()});window.addEventListener('appinstalled',function(){markInstalled()});if(navigator.getInstalledRelatedApps){navigator.getInstalledRelatedApps().then(function(apps){if(state.deferredPrompt)return;if(apps&&apps.some(function(app){return app&&app.platform==='webapp'})){markInstalled()}}).catch(function(){})}if('serviceWorker'in navigator){var ua=navigator.userAgent;var ios=/iPad|iPhone|iPod/.test(ua)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;if(!ios){navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(function(){})}}})();`;
