/**
 * Inlined in the document to capture beforeinstallprompt before React hydrates.
 * Kept as a string (not a public /pwa-install-init.js file) to avoid preload +
 * service-worker cross-world mismatch warnings in Chrome/Safari.
 *
 * Important: never treat service-worker presence as "installed" — Cosset always
 * registers a SW for push. Only standalone display-mode, appinstalled, and
 * same-origin getInstalledRelatedApps count.
 */
export const PWA_INSTALL_INIT_SCRIPT = `(function(){if(typeof window==='undefined')return;var STORAGE_KEY='cosset-pwa-installed';var state=window.__cossetPwaInstall=window.__cossetPwaInstall||{deferredPrompt:null,installed:false,initialized:false};if(state.initialized)return;state.initialized=true;function notify(){window.dispatchEvent(new Event('cosset-pwa-install-change'))}function clearInstalled(){state.installed=false;try{localStorage.removeItem(STORAGE_KEY)}catch(e){}}function markInstalled(){state.installed=true;state.deferredPrompt=null;try{localStorage.setItem(STORAGE_KEY,'1')}catch(e){}notify()}function isStandalone(){var modes=['standalone','minimal-ui','fullscreen'];var standalone=modes.some(function(mode){return window.matchMedia&&window.matchMedia('(display-mode: '+mode+')').matches});return standalone||window.navigator.standalone===true}function isSameOriginWebApp(app){if(!app||app.platform!=='webapp')return false;var candidate=app.url||app.id||'';if(!candidate)return false;try{return new URL(candidate,window.location.origin).origin===window.location.origin}catch(e){return candidate.indexOf(window.location.host)!==-1}}if(isStandalone()){markInstalled()}window.addEventListener('beforeinstallprompt',function(event){event.preventDefault();clearInstalled();state.deferredPrompt=event;notify()});window.addEventListener('appinstalled',function(){markInstalled()});if(navigator.getInstalledRelatedApps){navigator.getInstalledRelatedApps().then(function(apps){if(state.deferredPrompt)return;if(apps&&apps.some(isSameOriginWebApp)){markInstalled()}else if(!isStandalone()){clearInstalled();notify()}}).catch(function(){})}if('serviceWorker'in navigator){var ua=navigator.userAgent;var ios=/iPad|iPhone|iPod/.test(ua)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;if(!ios){navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(function(){})}}})();`;
