export const GLOBAL_EMOTICON_OPTIONS = [
  { label: 'Smile', value: '😀' },
  { label: 'Love', value: '😍' },
  { label: 'Laugh', value: '😂' },
  { label: 'Sad', value: '😢' },
  { label: 'Heart', value: '❤️' },
  { label: 'Party', value: '🎉' },
  { label: 'Thanks', value: '🙏' },
  { label: 'Cool', value: '😎' },
  { label: 'Surprised', value: '😮' },
  { label: 'Thinking', value: '🤔' },
  { label: 'Clap', value: '👏' },
  { label: 'Fire', value: '🔥' },
  { label: 'Like', value: '👍' },
  { label: 'Cry', value: '😭' },
  { label: 'Angry', value: '😡' },
  { label: 'Wow', value: '😲' },
  { label: 'Kiss', value: '😘' },
] as const;
